# Generated by Django 3.2.5 on 2021-08-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='inage_name',
            new_name='image_name',
        ),
    ]
